//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "books")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub library_id: Uuid,
    pub title: String,
    pub author: Option<String>,
    pub isbn: Option<String>,
    pub language: Option<String>,
    pub publisher: Option<String>,
    pub series: Option<String>,
    pub series_index: Option<i64>,
    pub page_count: Option<i64>,
    pub read_status: String,
    pub rating: Option<i64>,
    pub format: String,
    pub source_hash: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub keep_source: Option<bool>,
    pub sequence_index: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::annotations::Entity")]
    Annotations,
    #[sea_orm(has_many = "super::assets::Entity")]
    Assets,
    #[sea_orm(has_one = "super::book_ir::Entity")]
    BookIr,
    #[sea_orm(has_one = "super::book_metadata::Entity")]
    BookMetadata,
    #[sea_orm(has_many = "super::book_revisions::Entity")]
    BookRevisions,
    #[sea_orm(has_one = "super::comic_ir::Entity")]
    ComicIr,
    #[sea_orm(
        belongs_to = "super::libraries::Entity",
        from = "Column::LibraryId",
        to = "super::libraries::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Libraries,
    #[sea_orm(has_many = "super::reading_progress::Entity")]
    ReadingProgress,
    #[sea_orm(has_many = "super::shelf_entries::Entity")]
    ShelfEntries,
}

impl Related<super::annotations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Annotations.def()
    }
}

impl Related<super::assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assets.def()
    }
}

impl Related<super::book_ir::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookIr.def()
    }
}

impl Related<super::book_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookMetadata.def()
    }
}

impl Related<super::book_revisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookRevisions.def()
    }
}

impl Related<super::comic_ir::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComicIr.def()
    }
}

impl Related<super::libraries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Libraries.def()
    }
}

impl Related<super::reading_progress::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReadingProgress.def()
    }
}

impl Related<super::shelf_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShelfEntries.def()
    }
}

impl Related<super::shelves::Entity> for Entity {
    fn to() -> RelationDef {
        super::shelf_entries::Relation::Shelves.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::shelf_entries::Relation::Books.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
