//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "job_queue")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	pub kind: String,
	pub status: String,
	pub payload: Json,
	pub error: Option<String>,
	pub retry_count: i8,
	pub max_retries: i8,
	pub scheduled_at: Option<DateTimeWithTimeZone>,
	pub started_at: Option<DateTimeWithTimeZone>,
	pub completed_at: Option<DateTimeWithTimeZone>,
	pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
