//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod annotations;
pub mod assets;
pub mod book_ir;
pub mod book_metadata;
pub mod book_revisions;
pub mod bookmarks;
pub mod books;
pub mod comic_ir;
pub mod job_queue;
pub mod libraries;
pub mod metadata_cache;
pub mod reading_progress;
pub mod sessions;
pub mod shelf_entries;
pub mod shelves;
pub mod users;
