//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "shelf_entries")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub shelf_id: Uuid,
	#[sea_orm(primary_key, auto_increment = false)]
	pub book_id: Uuid,
	pub position: i64,
	pub added_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::books::Entity",
		from = "Column::BookId",
		to = "super::books::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Books,
	#[sea_orm(
		belongs_to = "super::shelves::Entity",
		from = "Column::ShelfId",
		to = "super::shelves::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Shelves,
}

impl Related<super::books::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Books.def()
	}
}

impl Related<super::shelves::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Shelves.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
