//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	#[sea_orm(unique)]
	pub email: String,
	pub password_hash: String,
	pub display_name: String,
	pub is_admin: bool,
	pub created_at: DateTimeWithTimeZone,
	pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::annotations::Entity")]
	Annotations,
	#[sea_orm(has_many = "super::libraries::Entity")]
	Libraries,
	#[sea_orm(has_many = "super::reading_progress::Entity")]
	ReadingProgress,
	#[sea_orm(has_many = "super::sessions::Entity")]
	Sessions,
	#[sea_orm(has_many = "super::shelves::Entity")]
	Shelves,
}

impl Related<super::annotations::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Annotations.def()
	}
}

impl Related<super::libraries::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Libraries.def()
	}
}

impl Related<super::reading_progress::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ReadingProgress.def()
	}
}

impl Related<super::sessions::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Sessions.def()
	}
}

impl Related<super::shelves::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Shelves.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
